# Inserts a blank line between shell prompts
add_newline = true

command_timeout = 10

format = """
$directory\
$git_branch\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[directory]
truncation_length = 5

[git_status]
ignore_submodules = true
