# Inserts a blank line between shell prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[directory]
truncation_length = 5
